version: "3.8"
services:
  make:
    image: aws-vpn-client_make
    build: .
    volumes:
      - .:/home/vpn/app
  connect:
    image: aws-vpn-client_connect
    container_name: aws-vpn
    build:
      context: ./
      dockerfile: ./connect/Dockerfile
    environment:
      - AWS_VPN_OVPN_BIN=./build/openvpn
      - AWS_VPN_OVPN_CONF=./build/ovpn.conf
      - AWS_VPN_ON_CHALLENGE=auto
      - AWS_VPN_VERBOSE=true
      - CHALLENGE_URL_COOKIE
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.disable_ipv6=0
    volumes:
      - ./build:/home/vpn/build
    ports:
      - 35001:35001
      - 3128:3128
      - 2222:22
