FROM alpine:latest

RUN apk add --no-cache \
    bash \
    git \
    patch

ARG USER=vpn
RUN adduser --disabled-password --gecos '' ${USER} \
    && mkdir -p app

WORKDIR "/home/$USER"
USER ${USER}:${USER}

RUN git clone https://github.com/OpenVPN/openvpn.git

# Copy entrypoint script into the container
COPY --chown=$USER:$USER entrypoints/gen-patch.sh entrypoint.sh

ENTRYPOINT ["/bin/bash", "entrypoint.sh"]
