version: "3.8"
services:
  make:
    container_name: aws-vpn-client_make
    build: .
    volumes:
      - ./build:/home/vpn/build
  connect:
    container_name: aws-vpn-client_connect
    build:
      context: ./
      dockerfile: ./connect/Dockerfile
    environment:
      - CHALLENGE_URL_COOKIE
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - 35001:35001
      - 3128:3128
      - 2222:22
    volumes:
      - ./connect:/home/vpn/connect
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true
