version: "3.8"
services:
  make:
    container_name: aws-vpn-client_make
    build: .
    volumes:
      - .:/home/vpn/app
  connect:
    container_name: aws-vpn-client_connect
    build:
      context: ./
      dockerfile: ./connect/Dockerfile
    environment:
      - AWS_VPN_OVPN_BIN=./openvpn
      - AWS_VPN_OVPN_CONF=./build/ovpn.conf
      - AWS_VPN_ON_CHALLENGE=auto
      - AWS_VPN_VERBOSE=true
      - CHALLENGE_URL_COOKIE
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    volumes:
      - ./build:/home/vpn/build
    ports:
      - 35001:35001
      - 3128:3128
      - 2222:22
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true
